package com.lzf.greendao.service.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lzf.greendao.entity.UserModel;
import com.lzf.greendao.entity.ChecksModel;

import com.lzf.greendao.service.greendao.UserModelDao;
import com.lzf.greendao.service.greendao.ChecksModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userModelDaoConfig;
    private final DaoConfig checksModelDaoConfig;

    private final UserModelDao userModelDao;
    private final ChecksModelDao checksModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userModelDaoConfig = daoConfigMap.get(UserModelDao.class).clone();
        userModelDaoConfig.initIdentityScope(type);

        checksModelDaoConfig = daoConfigMap.get(ChecksModelDao.class).clone();
        checksModelDaoConfig.initIdentityScope(type);

        userModelDao = new UserModelDao(userModelDaoConfig, this);
        checksModelDao = new ChecksModelDao(checksModelDaoConfig, this);

        registerDao(UserModel.class, userModelDao);
        registerDao(ChecksModel.class, checksModelDao);
    }
    
    public void clear() {
        userModelDaoConfig.clearIdentityScope();
        checksModelDaoConfig.clearIdentityScope();
    }

    public UserModelDao getUserModelDao() {
        return userModelDao;
    }

    public ChecksModelDao getChecksModelDao() {
        return checksModelDao;
    }

}
